import type { PaletteShape } from '@/types/config'

/** Aspect-correct preview container sizes for the shape palette sidebar. */
export const PALETTE_PREVIEW: Record<PaletteShape, { width: number; height: number }> = {
  terminator: { width: 44, height: 22 },
  process: { width: 40, height: 26 },
  decision: { width: 30, height: 30 },
  'input-output': { width: 38, height: 24 },
  database: { width: 34, height: 28 },
  document: { width: 34, height: 28 },
  connector: { width: 24, height: 24 },
  note: { width: 34, height: 28 },
  rectangle: { width: 40, height: 26 },
  circle: { width: 26, height: 26 },
  ellipse: { width: 38, height: 22 },
  hexagon: { width: 36, height: 26 },
  trapezoid: { width: 38, height: 24 },
  triangle: { width: 34, height: 26 },
  delay: { width: 38, height: 24 },
  'off-page': { width: 30, height: 30 },
  'manual-input': { width: 36, height: 26 },
  text: { width: 36, height: 18 },
  'swimlane-pool': { width: 44, height: 28 },
  'swimlane-lane': { width: 44, height: 24 },
  'swimlane-vertical': { width: 28, height: 36 },
  subprocess: { width: 40, height: 26 },
  'parallel-gateway': { width: 28, height: 28 },
  'or-gate': { width: 24, height: 24 },
  event: { width: 24, height: 24 },
  'data-store': { width: 36, height: 26 },
  display: { width: 38, height: 24 },
  annotation: { width: 38, height: 22 },
  'multi-document': { width: 34, height: 28 },
  card: { width: 36, height: 26 },
  'internal-storage': { width: 36, height: 26 },
  service: { width: 32, height: 32 },
}
